services:
  postgres:
    image: postgres:18-trixie
    container_name: postgres-demo
    volumes:
      - ./.postgresql_data:/var/lib/postgresql/18/docker
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: pgdemo #Tochange
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin1234
    ports:
      - "5432:5432"
  neo4j:
    image: neo4j:latest
    container_name: neo4j-demo
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./.neo4j:/data/import
      - ./.neo4j_data:/data
volumes:
  .postgresql_data:
  .neo4j_data:
